<a href="https://colab.research.google.com/github/ferdinandrafols/IA_LLMs/blob/main/GSI073_aula0_redes_neurais.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

GSI073 - Tópicos Especiais de Inteligência Artificial

Definição dos dados

In [2]:
import torch; import sklearn; from torch import nn

# 1. Carregar dados
iris = sklearn.datasets.load_iris()
X = iris.data        # 4 features: sépalas e pétalas
y = (iris.target == 1).astype(float)  # 1 se Versicolor, 0 caso contrário

# 2. Preparar dados para pytorch
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32).view(-1, 1)

# Adicionar print para ver o resultado
print("Variável X (features):")
print(X)
print("\nVariável y (target):")
print(y)

Variável X (features):
tensor([[5.1000, 3.5000, 1.4000, 0.2000],
        [4.9000, 3.0000, 1.4000, 0.2000],
        [4.7000, 3.2000, 1.3000, 0.2000],
        [4.6000, 3.1000, 1.5000, 0.2000],
        [5.0000, 3.6000, 1.4000, 0.2000],
        [5.4000, 3.9000, 1.7000, 0.4000],
        [4.6000, 3.4000, 1.4000, 0.3000],
        [5.0000, 3.4000, 1.5000, 0.2000],
        [4.4000, 2.9000, 1.4000, 0.2000],
        [4.9000, 3.1000, 1.5000, 0.1000],
        [5.4000, 3.7000, 1.5000, 0.2000],
        [4.8000, 3.4000, 1.6000, 0.2000],
        [4.8000, 3.0000, 1.4000, 0.1000],
        [4.3000, 3.0000, 1.1000, 0.1000],
        [5.8000, 4.0000, 1.2000, 0.2000],
        [5.7000, 4.4000, 1.5000, 0.4000],
        [5.4000, 3.9000, 1.3000, 0.4000],
        [5.1000, 3.5000, 1.4000, 0.3000],
        [5.7000, 3.8000, 1.7000, 0.3000],
        [5.1000, 3.8000, 1.5000, 0.3000],
        [5.4000, 3.4000, 1.7000, 0.2000],
        [5.1000, 3.7000, 1.5000, 0.4000],
        [4.6000, 3.6000, 1.0000, 0.2000],
        [5.

Vamos interpretar o que você está vendo.

---

## 1. O que é o **X** (features)

Trecho do início de `X`:

```text
tensor([[5.1000, 3.5000, 1.4000, 0.2000],
        [4.9000, 3.0000, 1.4000, 0.2000],
        ...
```

Isso significa:

* `X` é um tensor de shape **[150, 4]** (150 linhas, 4 colunas).
* Cada **linha** = 1 flor (1 observação do dataset Iris).
* Cada **coluna** = 1 característica (*feature*):

  1. comprimento da sépala
  2. largura da sépala
  3. comprimento da pétala
  4. largura da pétala

Então, por exemplo:

```text
[5.1000, 3.5000, 1.4000, 0.2000]
```

→ é uma flor com:

* sépala 5.1 × 3.5
* pétala 1.4 × 0.2

As primeiras 50 linhas, como você vê pelos números pequenos de pétala (≈ 1.x), são da classe **Setosa**.

---

## 2. O que é o **y** (target binário)

Trecho do início de `y`:

```text
tensor([[0.],
        [0.],
        [0.],
        ...
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        ...
        [1.],
        [1.],
        [0.],
        [0.],
        ...
```

Aqui está a mágica:

Você definiu:

```python
y = (iris.target == 1).astype(float)
```

Isso transforma o problema em **classificação binária**:

* `1.0` → a flor é **Versicolor** (classe 1 no Iris)
* `0.0` → a flor **não é Versicolor** (ou seja, é Setosa (0) ou Virginica (2))

O padrão do Iris é:

* amostras 0–49 → Setosa (classe 0) → viram `0.`
* amostras 50–99 → Versicolor (classe 1) → viram `1.`
* amostras 100–149 → Virginica (classe 2) → viram `0.`

E é exatamente isso que o seu `y` mostra:

* um bloco grande de **0.** no começo (Setosa) ✅
* um bloco de **1.** no meio (Versicolor) ✅
* um bloco de **0.** no final (Virginica) ✅

Ou seja: o *target* está correto para a tarefa

> “prever se a flor é Versicolor (1) ou não (0)”.

---

## 3. Estrutura está perfeita pra ML / PyTorch

Você agora tem:

* `X`: `torch.Size([150, 4])`, `dtype=torch.float32`
* `y`: `torch.Size([150, 1])`, `dtype=torch.float32`

Isso está **perfeito** para:

* dividir em treino/teste,
* jogar num modelo `nn.Linear(4, 1)` (regressão logística),
* treinar com `BCEWithLogitsLoss`.


In [3]:

# 3. Definir modelo
import torch.nn.functional as F
class RedeNeural(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(RedeNeural, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, output_dim)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x